(function () {
  "use strict";
  var signals = ["owner", "evidence", "intervene", "execute", "learn"];
  var labels = { owner: "Decision owner", evidence: "Usable evidence", intervene: "Ability to intervene", execute: "Safe execution", learn: "Learning loop" };
  var readyText = { owner: "Named owner, backup, and authority are available.", evidence: "Current sources, freshness, and gaps are visible.", intervene: "A reviewer can act in time and override.", execute: "The action is gated, recorded, and recoverable.", learn: "Outcomes and exceptions will be reviewed." };
  var weakText = { owner: "No reliable owner and backup are available now.", evidence: "The evidence cannot be trusted or checked quickly enough.", intervene: "The human review is not operationally meaningful.", execute: "The execution or recovery control is unclear.", learn: "The organization will not retain the outcome as learning." };
  var presets = { friday: { owner:"weak", evidence:"weak", intervene:"weak", execute:"weak", learn:"weak" }, shadow: { owner:"ready", evidence:"ready", intervene:"weak", execute:"weak", learn:"ready" }, pilot: { owner:"ready", evidence:"ready", intervene:"ready", execute:"ready", learn:"ready" } };
  var form = document.getElementById("readiness-form"), result = document.getElementById("readiness-result"), status = document.getElementById("result-status"), title = document.getElementById("result-title"), copy = document.getElementById("result-copy"), score = document.getElementById("readiness-score"), summary = document.getElementById("signal-summary"), list = document.getElementById("signal-list"), output = document.getElementById("readiness-output"), copyButton = document.getElementById("copy-readiness"), copyStatus = document.getElementById("copy-status"), motion = window.matchMedia("(prefers-reduced-motion: reduce)");
  var buttons = { friday: document.getElementById("load-friday"), shadow: document.getElementById("load-shadow"), pilot: document.getElementById("load-pilot") };
  function value(name){ var input = form.querySelector('[name="' + name + '"]:checked'); return input ? input.value : "weak"; }
  function setButtons(active){ Object.keys(buttons).forEach(function(key){ buttons[key].classList.toggle("active", key === active); buttons[key].setAttribute("aria-pressed", String(key === active)); }); }
  function render(focus){ var count = signals.filter(function(signal){ return value(signal) === "ready"; }).length; score.textContent = count + "/5 signals"; summary.textContent = count + " ready"; list.replaceChildren(); signals.forEach(function(signal){ var ready = value(signal) === "ready", item = document.createElement("li"), name = document.createElement("strong"), detail = document.createElement("span"); item.className = ready ? "ready" : "weak"; name.textContent = labels[signal]; detail.textContent = ready ? readyText[signal] : weakText[signal]; item.append(name, detail); list.appendChild(item); });
    if(count === 5){ status.textContent="READY FOR BOUNDED PILOT"; status.className="result-status ready"; title.textContent="The organization can receive a recommendation and operate it with controls."; copy.textContent="Start with the documented boundary: the agent recommends, a named owner decides, execution is gated, and outcomes are reviewed before scope expands."; }
    else if(count >= 3){ status.textContent="READY FOR SHADOW MODE"; status.className="result-status assist"; title.textContent="The agent can learn alongside the work. The organization should not yet rely on it to move the work."; copy.textContent="Use recommendations for observation and comparison. Close the missing operating signals before the agent’s output changes a live outcome."; }
    else { status.textContent="NOT READY TO PILOT"; status.className="result-status stop"; title.textContent="A capable recommendation has nowhere reliable to land."; copy.textContent="The agent can identify the exception. It cannot create an available decision owner, current evidence, an override path, or an accountable recovery process."; }
    output.value = ["OPERATING READINESS BRIEF — INVOICE EXCEPTION", "Scenario: Friday 16:50. The agent detects a 6.2% invoice mismatch and recommends holding payment pending a documented supply-continuity override.", "", "Model capability: recognition, evidence display, uncertainty statement, and recommendation are assumed available for this educational drill.", "", "Operating signals:", signals.map(function(signal){ return "- " + labels[signal] + ": " + (value(signal) === "ready" ? "READY — " + readyText[signal] : "GAP — " + weakText[signal]); }).join("\n"), "", "Verdict: " + status.textContent + ".", "Next control: " + (count === 5 ? "Run a bounded pilot with override and outcome review." : count >= 3 ? "Keep the agent in shadow mode; close the listed gaps before using its output in a live decision." : "Do not start a live pilot. Make the missing human operating capabilities explicit first."), "", "Boundary: educational design exercise; not a model evaluation, legal assessment, or production approval."].join("\n");
    if(focus){ result.focus({preventScroll:true}); result.scrollIntoView({behavior:motion.matches?"auto":"smooth",block:"start"}); }
  }
  function setPreset(name, focus){ signals.forEach(function(signal){ form.querySelector('[name="'+signal+'"][value="'+presets[name][signal]+'"]').checked=true; }); setButtons(name); render(focus); }
  Object.keys(buttons).forEach(function(name){ buttons[name].addEventListener("click",function(){setPreset(name,true);}); });
  form.addEventListener("input", function(){setButtons("");render(false);}); form.addEventListener("submit",function(event){event.preventDefault();render(true);}); form.addEventListener("reset",function(){window.setTimeout(function(){setPreset("friday",false);},0);});
  copyButton.addEventListener("click",function(){navigator.clipboard.writeText(output.value).then(function(){copyStatus.textContent="Copied";window.setTimeout(function(){copyStatus.textContent="";},2200);}).catch(function(){output.select();document.execCommand("copy");copyStatus.textContent="Copied";});}); render(false);
}());
