(function(){
  "use strict";
  var form=document.getElementById("pilot-form"),result=document.getElementById("pilot-result"),output=document.getElementById("pilot-output"),status=document.getElementById("pilot-status"),progress=document.getElementById("card-progress"),summary=document.getElementById("pilot-summary"),copyButton=document.getElementById("copy-pilot"),copyStatus=document.getElementById("copy-status"),exampleButton=document.getElementById("load-example"),blankButton=document.getElementById("start-blank"),rehearsalResult=document.getElementById("rehearsal-result"),rehearsed=new Set(),motion=window.matchMedia("(prefers-reduced-motion: reduce)");
  var example={decision:"Should Invoice 447 be held, paid or escalated?",trigger:"Mismatch exceeds 5% or supply is at risk.",evidence:"Invoice, purchase order, receipt, contract and supplier warning.",owner:"Finance Controller; Procurement Director is backup.",allowed:"Gather evidence, compare records and recommend a next step.",stop:"Evidence is stale, owner is unavailable, or action would release payment.",moves:["Agent","Together","Agent","Human","Human","Agent"]};
  var rehearsals={stale:["Pause and label the evidence gap.","Do not infer missing facts. Refresh the source or escalate."],away:["Route to the named backup.","If neither owner can act in time, hold the case at the safe state."],wrong:["Stop the action, retain the evidence and override reason, recover safely, then update the rule before the next case."]};
  function field(name){return form.elements[name].value.trim();}
  function checked(name){return [].slice.call(form.querySelectorAll('input[name="'+name+'"]:checked')).map(function(item){return item.value;});}
  function moves(){return ["find","check","suggest","decide","act","watch"].map(function(move){return move[0].toUpperCase()+move.slice(1)+": "+form.elements["move-"+move].value;});}
  function setPreset(blank){var names=["decision","trigger","evidence","owner","allowed","stop"];names.forEach(function(name){form.elements[name].value=blank?"":example[name];});["find","check","suggest","decide","act","watch"].forEach(function(move,index){form.elements["move-"+move].value=blank?"Human":example.moves[index];});form.querySelectorAll('input[name="rule"],input[name="metric"]').forEach(function(item){item.checked=!blank;});rehearsed.clear();document.querySelectorAll("[data-rehearsal]").forEach(function(button){button.classList.remove("done");button.setAttribute("aria-pressed","false");});rehearsalResult.innerHTML="<strong>Choose a failure.</strong><p>The playbook will show the expected safe response.</p>";exampleButton.classList.toggle("active",!blank);exampleButton.setAttribute("aria-pressed",String(!blank));blankButton.classList.toggle("active",blank);blankButton.setAttribute("aria-pressed",String(blank));render(false);if(blank)form.elements.decision.focus();}
  function render(focus){var required=["decision","trigger","evidence","owner","allowed","stop"],explained=required.every(function(name){return field(name).length>0;}),rules=checked("rule"),metrics=checked("metric"),ready=[field("decision").length>0,explained,rules.length>0,rehearsed.size===3,metrics.length>0,true],count=ready.filter(Boolean).length;progress.textContent=count+"/6 ready";if(count===6){status.textContent="READY FOR A SMALL PILOT";status.className="result-status ready";summary.textContent="The card is clear enough to discuss. Keep the first pilot small and require evidence before expanding authority.";}else if(count>=4){status.textContent="REHEARSE BEFORE PILOT";status.className="result-status assist";summary.textContent="The shape is useful, but finish the missing lines, stop rules, failure rehearsals, or measures before live work.";}else{status.textContent="MAKE THE DECISION SMALLER";status.className="result-status stop";summary.textContent="Start with one decision and explain it in plain language before choosing technology or autonomy.";}
    output.value=["ONE DECISION PILOT CARD", "", "DECISION", field("decision")||"[Write one decision as a question]", "", "EXPLAIN IT IN FIVE LINES", "Starts when: "+(field("trigger")||"[not defined]"), "Check: "+(field("evidence")||"[not defined]"), "Human owner: "+(field("owner")||"[not defined]"), "Agent may: "+(field("allowed")||"[not defined]"), "Agent stops when: "+(field("stop")||"[not defined]"), "", "DIVIDE THE MOVES", moves().join("\n"), "", "STOP RULES", rules.length?rules.map(function(rule){return "- "+rule;}).join("\n"):"- [none selected]", "", "BAD-DAY REHEARSAL", "Completed: "+(rehearsed.size?Array.from(rehearsed).join(", "):"none"), "", "MEASURE", metrics.length?metrics.map(function(metric){return "- "+metric;}).join("\n"):"- [none selected]", "", "NEXT AUTHORITY RULE", "Do not expand authority because the demo looked good. Let observed decisions, recoveries, and business outcomes earn the next move.", "", "STATUS: "+status.textContent, "", "Educational planning aid; not production approval."].join("\n");if(focus){result.focus({preventScroll:true});result.scrollIntoView({behavior:motion.matches?"auto":"smooth",block:"start"});}}
  document.querySelectorAll("[data-rehearsal]").forEach(function(button){button.setAttribute("aria-pressed","false");button.addEventListener("click",function(){var key=button.dataset.rehearsal,replies=rehearsals[key];rehearsed.add(key);button.classList.add("done");button.setAttribute("aria-pressed","true");rehearsalResult.innerHTML="<strong>Safe response</strong><p>"+replies.join(" ")+"</p>";render(false);});});
  form.addEventListener("input",function(){exampleButton.classList.remove("active");blankButton.classList.remove("active");exampleButton.setAttribute("aria-pressed","false");blankButton.setAttribute("aria-pressed","false");render(false);});form.addEventListener("submit",function(event){event.preventDefault();render(true);});form.addEventListener("reset",function(){window.setTimeout(function(){setPreset(false);},0);});exampleButton.addEventListener("click",function(){setPreset(false);});blankButton.addEventListener("click",function(){setPreset(true);});copyButton.addEventListener("click",function(){navigator.clipboard.writeText(output.value).then(function(){copyStatus.textContent="Copied";window.setTimeout(function(){copyStatus.textContent="";},2200);}).catch(function(){output.select();document.execCommand("copy");copyStatus.textContent="Copied";});});render(false);
}());
